# Generated by Django 4.2.16 on 2026-05-07 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0011_listing_about_platform"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="قیمت پیشنهادی"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="پیام")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پاسخ"),
                            ("accepted", "پذیرفته شده"),
                            ("rejected", "رد شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "seller_response",
                    models.TextField(blank=True, verbose_name="پاسخ فروشنده"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_proposals",
                        to="listings.listing",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیشنهاد قیمت",
                "verbose_name_plural": "پیشنهادهای قیمت",
                "ordering": ["-created_at"],
                "unique_together": {("listing", "buyer")},
            },
        ),
    ]
