# Generated by Django 4.2.16 on 2026-05-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_chatroom_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceproposal",
            name="buyer_agreed",
            field=models.BooleanField(default=False, verbose_name="خریدار موافق"),
        ),
        migrations.AddField(
            model_name="priceproposal",
            name="buyer_cancelled",
            field=models.BooleanField(default=False, verbose_name="خریدار کنسل کرد"),
        ),
        migrations.AddField(
            model_name="priceproposal",
            name="seller_agreed",
            field=models.BooleanField(default=False, verbose_name="فروشنده موافق"),
        ),
        migrations.AddField(
            model_name="priceproposal",
            name="seller_cancelled",
            field=models.BooleanField(default=False, verbose_name="فروشنده کنسل کرد"),
        ),
        migrations.AlterField(
            model_name="priceproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پاسخ"),
                    ("accepted", "پذیرفته شده"),
                    ("rejected", "رد شده"),
                    ("cancelled", "لغو شده"),
                    ("negotiating", "در حال گفتگو"),
                    ("deal_confirmed", "توافق شد"),
                    ("deal_cancelled", "کنسل شد"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
