# Generated by Django 4.2.16 on 2026-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_priceproposal_buyer_agreed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceproposal",
            name="buyer_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="priceproposal",
            name="seller_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
