# Generated by Django 4.2.16 on 2026-05-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True, verbose_name="دلیل رد"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار تایید"),
                    ("active", "فعال"),
                    ("sold", "فروخته شده"),
                    ("rejected", "رد شده"),
                    ("deleted", "حذف شده"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
