# Generated by Django 4.2.16 on 2026-05-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_rejection_reason_alter_listing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incomeproof",
            options={
                "verbose_name": "اثبات درآمد",
                "verbose_name_plural": "اثبات\u200cهای درآمد",
            },
        ),
        migrations.RemoveField(
            model_name="incomeproof",
            name="file",
        ),
        migrations.RemoveField(
            model_name="incomeproof",
            name="proof_type",
        ),
        migrations.AddField(
            model_name="incomeproof",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="income_proofs/",
                verbose_name="تصویر اثبات درآمد",
            ),
        ),
        migrations.AlterField(
            model_name="incomeproof",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
    ]
