# Generated by Django 4.2.16 on 2026-05-06 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0003_alter_incomeproof_options_remove_incomeproof_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="آگهی خصوصی"),
        ),
        migrations.CreateModel(
            name="VisitRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تایید"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="پیام درخواست")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_requests",
                        to="listings.listing",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست بازدید",
                "verbose_name_plural": "درخواست\u200cهای بازدید",
                "ordering": ["-created_at"],
                "unique_together": {("listing", "requester")},
            },
        ),
    ]
