# Generated by Django 4.2.16 on 2026-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_is_private_visitrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="discount_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
