# Generated by Django 4.2.16 on 2026-05-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_discount_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
    ]
