# Generated by Django 4.2.16 on 2026-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_alter_listing_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_preferment",
            field=models.BooleanField(default=False, verbose_name="آگهی ارتقا یافته"),
        ),
        migrations.AddField(
            model_name="listing",
            name="location",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="most_comment",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="most_like",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="most_view",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="platform_age",
            field=models.IntegerField(default=0),
        ),
    ]
