# Generated by Django 4.2.16 on 2026-05-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_listing_is_preferment_listing_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "مبتدی"),
                    ("intermediate", "متوسط"),
                    ("advanced", "پیشرفته"),
                    ("professional", "حرفه\u200cای"),
                ],
                default="beginner",
                max_length=20,
                verbose_name="سطح",
            ),
        ),
        migrations.CreateModel(
            name="ViewsDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("views", models.IntegerField(verbose_name="بازدید")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views_data_points",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "نقطه داده بازدید",
                "verbose_name_plural": "نقاط داده بازدید",
                "ordering": ["date"],
                "unique_together": {("listing", "date")},
            },
        ),
        migrations.CreateModel(
            name="IncomeDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "income",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="درآمد"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_data_points",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "نقطه داده درآمد",
                "verbose_name_plural": "نقاط داده درآمد",
                "ordering": ["date"],
                "unique_together": {("listing", "date")},
            },
        ),
    ]
