# Generated by Django 4.2.16 on 2026-05-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_listing_level_viewsdatapoint_incomedatapoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="level",
        ),
        migrations.AddField(
            model_name="listing",
            name="is_income",
            field=models.BooleanField(default=True, verbose_name="اگهی به درامد رسیده"),
        ),
        migrations.AddField(
            model_name="listing",
            name="is_verified",
            field=models.BooleanField(
                default=False, verbose_name="اطلاعات مورد تایید است"
            ),
        ),
    ]
