# Generated by Django 4.2.16 on 2026-05-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_remove_listing_level_listing_is_income_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="monthly_income",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
    ]
