# Generated by Django 4.2.16 on 2026-05-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_alter_listing_monthly_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="about_platform",
            field=models.TextField(blank=True, null=True),
        ),
    ]
