# Generated by Django 4.2.16 on 2026-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_listing_about_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="about_platform",
            field=models.TextField(blank=True, null=True, verbose_name="درباره پلتفرم"),
        ),
    ]
