# Generated by Django 4.2.16 on 2026-05-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_alter_listing_about_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="پرسش")),
                ("answer", models.TextField(verbose_name="پاسخ")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرسش و پاسخ",
                "verbose_name_plural": "پرسش\u200cها و پاسخ\u200cها",
                "ordering": ["order", "id"],
            },
        ),
    ]
