# Generated by Django 4.2.16 on 2026-05-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0013_listingfaq"),
        ("listings", "0014_add_default_categories"),
    ]

    operations = []
