# Generated by Django 4.2.16 on 2026-05-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0015_merge_0013_listingfaq_0014_add_default_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingfaq",
            name="answer",
            field=models.TextField(blank=True, verbose_name="پاسخ"),
        ),
        migrations.AlterField(
            model_name="listingfaq",
            name="question",
            field=models.CharField(blank=True, max_length=300, verbose_name="پرسش"),
        ),
    ]
