# Generated by Django 4.2.16 on 2026-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0016_alter_listingfaq_answer_alter_listingfaq_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="is_preferment",
        ),
        migrations.AddField(
            model_name="listing",
            name="premium",
            field=models.BooleanField(default=False, verbose_name="آگهی ارتقا ویژه"),
        ),
        migrations.AddField(
            model_name="listing",
            name="pro",
            field=models.BooleanField(default=False, verbose_name="آگهی ارتقا پرو"),
        ),
        migrations.AlterField(
            model_name="listingfaq",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="ترتیب"
            ),
        ),
    ]
