# Generated by Django 4.2.16 on 2026-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0017_remove_listing_is_preferment_listing_premium_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="premium",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="pro",
        ),
        migrations.AddField(
            model_name="listing",
            name="boost",
            field=models.BooleanField(default=False, verbose_name="آگهی پیشرفته"),
        ),
        migrations.AddField(
            model_name="listing",
            name="premier",
            field=models.BooleanField(default=False, verbose_name="آگهی برتر"),
        ),
    ]
