# Generated by Django 4.2.16 on 2026-05-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0018_remove_listing_premium_remove_listing_pro_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["-boost", "-created_at"]},
        ),
    ]
