# Generated by Django 4.2.16 on 2026-05-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0019_alter_listing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="analyst",
            field=models.TextField(blank=True, null=True, verbose_name="درباره پلتفرم"),
        ),
    ]
