# Generated by Django 4.2.16 on 2026-05-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0020_listing_analyst"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="analyst",
            field=models.TextField(
                blank=True, null=True, verbose_name="تحلیلگر و مشاور"
            ),
        ),
    ]
