# Generated by Django 4.2.16 on 2026-05-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0021_alter_listing_analyst"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingAnalyst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analyst_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="نام تحلیلگر",
                    ),
                ),
                (
                    "analyst_expertise",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="تخصص"
                    ),
                ),
                (
                    "analyst_education",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="تحصیلات"
                    ),
                ),
                (
                    "analyst_record",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="سابقه"
                    ),
                ),
                (
                    "analyst",
                    models.TextField(
                        blank=True, null=True, verbose_name="تحلیلگر و مشاور"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="listing",
            name="analyst",
        ),
    ]
