# Generated by Django 4.2.16 on 2026-05-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0022_listinganalyst_remove_listing_analyst"),
    ]

    operations = [
        migrations.AddField(
            model_name="listinganalyst",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysts",
                to="listings.listing",
            ),
        ),
    ]
