# Generated by Django 4.2.16 on 2026-05-20 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0024_alter_listinganalyst_listing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="listing",
            options={
                "ordering": ["-boost", "-premier", "-created_at"],
                "verbose_name": "آگهی",
                "verbose_name_plural": "آگهی\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="listinganalyst",
            options={"verbose_name": "تحلیلگر", "verbose_name_plural": "تحلیلگران"},
        ),
        migrations.RemoveField(
            model_name="listinganalyst",
            name="analyst",
        ),
        migrations.AddField(
            model_name="listing",
            name="avg_monthly_profit",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="میانگین سود ماهانه",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="avg_monthly_revenue",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="میانگین درآمد ماهانه",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="post_sale_support",
            field=models.TextField(
                blank=True, null=True, verbose_name="پشتیبانی پس از فروش"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="profit_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="حاشیه سود (درصد)",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="profit_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ضریب سود",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="revenue_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ضریب درآمد",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="total_profit",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="سود کل",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="total_revenue",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="درآمد کل",
            ),
        ),
        migrations.AddField(
            model_name="listinganalyst",
            name="analyst_description",
            field=models.TextField(blank=True, verbose_name="توضیحات تحلیلگر"),
        ),
        migrations.AddField(
            model_name="listinganalyst",
            name="analyst_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="analysts/",
                verbose_name="تصویر تحلیلگر",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="category",
            name="platform",
            field=models.CharField(
                choices=[
                    ("website", "وبسایت"),
                    ("instagram", "اینستاگرام"),
                    ("telegram", "تلگرام"),
                    ("youtube", "یوتیوب"),
                    ("aparat", "آپارات"),
                    ("other", "سایر"),
                ],
                max_length=20,
                verbose_name="پلتفرم",
            ),
        ),
        migrations.AlterField(
            model_name="incomedatapoint",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="income_data_points",
                to="listings.listing",
                verbose_name="آگهی",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="قیمت با تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="followers_count",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="تعداد فالوور"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="is_income",
            field=models.BooleanField(default=True, verbose_name="آگهی به درآمد رسیده"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="موقعیت"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="main_image",
            field=models.ImageField(
                upload_to="listings/images/", verbose_name="تصویر اصلی"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="monthly_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="درآمد ماهانه",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="most_comment",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="بیشترین کامنت"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="most_like",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="بیشترین لایک"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="most_view",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="بیشترین بازدید"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="platform_age",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="سن پلتفرم (ماه)"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="platform_url",
            field=models.URLField(blank=True, verbose_name="آدرس پلتفرم"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="قیمت"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="فروشنده",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار تایید"),
                    ("active", "فعال"),
                    ("sold", "فروخته شده"),
                    ("rejected", "رد شده"),
                    ("deleted", "حذف شده"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="تعداد بازدید"),
        ),
        migrations.AlterField(
            model_name="listinganalyst",
            name="analyst_education",
            field=models.CharField(blank=True, max_length=200, verbose_name="تحصیلات"),
        ),
        migrations.AlterField(
            model_name="listinganalyst",
            name="analyst_expertise",
            field=models.CharField(blank=True, max_length=200, verbose_name="تخصص"),
        ),
        migrations.AlterField(
            model_name="listinganalyst",
            name="analyst_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="نام تحلیلگر"
            ),
        ),
        migrations.AlterField(
            model_name="listinganalyst",
            name="analyst_record",
            field=models.CharField(blank=True, max_length=200, verbose_name="سابقه"),
        ),
        migrations.AlterField(
            model_name="listinganalyst",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_analyst",
                to="listings.listing",
                verbose_name="آگهی",
            ),
        ),
        migrations.AlterField(
            model_name="viewsdatapoint",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views_data_points",
                to="listings.listing",
                verbose_name="آگهی",
            ),
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "توییتر"),
                            ("instagram", "اینستاگرام"),
                            ("github", "گیت\u200cهاب"),
                            ("facebook", "فیسبوک"),
                            ("linkedin", "لینکدین"),
                            ("telegram", "تلگرام"),
                            ("other", "سایر"),
                        ],
                        max_length=20,
                        verbose_name="پلتفرم",
                    ),
                ),
                (
                    "followers",
                    models.CharField(max_length=100, verbose_name="تعداد فالوور"),
                ),
                ("url", models.URLField(blank=True, verbose_name="لینک")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_medias",
                        to="listings.listing",
                        verbose_name="آگهی",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسانه اجتماعی",
                "verbose_name_plural": "رسانه\u200cهای اجتماعی",
            },
        ),
        migrations.CreateModel(
            name="ServiceUsed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=200, verbose_name="نام خدمت"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_used",
                        to="listings.listing",
                        verbose_name="آگهی",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت مورد استفاده",
                "verbose_name_plural": "خدمات مورد استفاده",
            },
        ),
        migrations.CreateModel(
            name="SaleInclude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(max_length=200, verbose_name="نام دارایی"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_includes",
                        to="listings.listing",
                        verbose_name="آگهی",
                    ),
                ),
            ],
            options={
                "verbose_name": "دارایی فروش",
                "verbose_name_plural": "دارایی\u200cهای فروش",
            },
        ),
        migrations.CreateModel(
            name="MonetizationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_name",
                    models.CharField(max_length=200, verbose_name="نام روش"),
                ),
                (
                    "icon_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نوع آیکون"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monetization_methods",
                        to="listings.listing",
                        verbose_name="آگهی",
                    ),
                ),
            ],
            options={
                "verbose_name": "روش کسب درآمد",
                "verbose_name_plural": "روش\u200cهای کسب درآمد",
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_name",
                    models.CharField(max_length=200, verbose_name="نام مجوز"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="listings.listing",
                        verbose_name="آگهی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجوز",
                "verbose_name_plural": "مجوزها",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_name",
                    models.CharField(max_length=200, verbose_name="نام هزینه"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="مبلغ"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "ماهانه"),
                            ("yearly", "سالانه"),
                            ("one_time", "یکبار"),
                        ],
                        max_length=20,
                        verbose_name="دوره",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="listings.listing",
                        verbose_name="آگهی",
                    ),
                ),
            ],
            options={
                "verbose_name": "هزینه",
                "verbose_name_plural": "هزینه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="attachments/", verbose_name="فایل"),
                ),
                (
                    "file_name",
                    models.CharField(max_length=200, verbose_name="نام فایل"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="listings.listing",
                        verbose_name="آگهی",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیوست",
                "verbose_name_plural": "پیوست\u200cها",
            },
        ),
    ]
