# Generated by Django 4.2.16 on 2026-05-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0026_remove_monetizationmethod_icon_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monetizationmethod",
            name="method",
            field=models.CharField(
                choices=[
                    ("banner_click_advertising", "تبلیغات بنری و کلیکی"),
                    ("sponsored_posts", "پست\u200cهای حمایت\u200cشده"),
                    ("cooperation_sales", "همکاری در فروش"),
                    ("special_subscription_sale", "فروش اشتراک ویژه"),
                    ("selling_digital_products", "فروش محصولات دیجیتال"),
                    ("selling_physical_products", "فروش محصولات فیزیکی"),
                    ("receive_financial_support", "دریافت حمایت مالی"),
                    (
                        "holding_training_courses",
                        "برگزاری دوره\u200cهای آموزشی و وبینار",
                    ),
                    ("sell_\u200b\u200bbacklinks", "فروش بک\u200cلینک و فضای تبلیغاتی"),
                    ("providing_consulting_services", "ارائه خدمات مشاوره و فریلنسری"),
                ],
                max_length=50,
                verbose_name="روش",
            ),
        ),
    ]
