# Generated by Django 4.2.16 on 2026-05-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0027_alter_monetizationmethod_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleinclude",
            name="post_sale_support",
            field=models.CharField(
                blank=True,
                max_length=2000,
                null=True,
                verbose_name="پشتیبانی پس از فروش",
            ),
        ),
    ]
