# Generated by Django 4.2.16 on 2026-05-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0028_saleinclude_post_sale_support"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleinclude",
            name="post_sale_support",
        ),
    ]
