# Generated by Django 4.2.16 on 2026-05-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0029_remove_saleinclude_post_sale_support"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="file_name",
        ),
    ]
