# Generated by Django 4.2.16 on 2026-05-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0030_remove_attachment_file_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmedInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmed_name",
                    models.CharField(
                        max_length=200, verbose_name="نام اطلاعات تایید شده"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmed",
                        to="listings.listing",
                        verbose_name="آگهی",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات تایید",
                "verbose_name_plural": "اطلاعاتات تایید",
            },
        ),
    ]
