# Generated by Django 4.2.16 on 2026-05-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0032_savedlisting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SavedListing",
        ),
    ]
