# Generated by Django 4.2.16 on 2026-05-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0033_delete_savedlisting"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="suggested_price",
            field=models.BooleanField(default=False, verbose_name="امکان پیشنهاد قیمت"),
        ),
    ]
