# Generated by Django 4.2.16 on 2026-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0034_listing_suggested_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="areas_activity",
            field=models.CharField(
                choices=[
                    ("shopping_commerce", "فروشگاهی و تجارت الکترونیک"),
                    ("technology_software", "تکنولوژی و نرم\u200cافزار "),
                    ("education_learning", "آموزش و یادگیری"),
                    ("health_medicine_beauty", "سلامت، پزشکی و زیبایی"),
                    ("news_magazines_portals", "خبری، مجله و پورتال"),
                    (
                        "finance_stock_exchange_cryptocurrency",
                        "مالی، بورس و ارز دیجیتال",
                    ),
                    ("entertainment_games_movies", "سرگرمی، بازی و فیلم"),
                    ("lifestyle_fashion_fashion", "سبک زندگی، مد و فشن"),
                    ("travel_tourism_immigration", "سفر، گردشگری و مهاجرت"),
                    ("real_estate", "املاک و مستغلات"),
                    ("corporate_B2B_services", "خدمات شرکتی و B2B"),
                    ("sports_fitness", "ورزشی و تناسب اندام"),
                    ("food_cooking_restaurants", "غذا، آشپزی و رستوران"),
                    ("home_decoration_architecture", "خانه، دکوراسیون و معماری"),
                    ("pets", "حیوانات خانگی"),
                    ("other", "سایر"),
                ],
                default="other",
                max_length=60,
                verbose_name="حوزه\u200c فعالیت",
            ),
            preserve_default=False,
        ),
    ]
