# Generated by Django 4.2.16 on 2026-05-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0036_listing_sale_reason_listing_sale_reason_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="technologyused",
            name="category",
            field=models.CharField(
                choices=[
                    ("cms", "CMS / فروشگاه\u200cساز"),
                    ("backend", "Backend"),
                    ("frontend", "Frontend"),
                    ("database", "Database"),
                    ("infrastructure", "Infrastructure"),
                    ("mobile", "Mobile"),
                    ("devops", "DevOps"),
                    ("third_party", "سرویس\u200cهای جانبی"),
                ],
                default="backend",
                max_length=20,
                verbose_name="دسته\u200cبندی",
            ),
        ),
    ]
