# Generated by Django 4.2.16 on 2026-05-31 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0038_alter_technologyused_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="technologyused",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="technologyused",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technologies_used",
                to="listings.listing",
                verbose_name="آگهی",
            ),
        ),
        migrations.AlterField(
            model_name="technologyused",
            name="technology_backend",
            field=models.JSONField(
                blank=True, default=list, verbose_name="تکنولوژی Backend"
            ),
        ),
        migrations.AlterField(
            model_name="technologyused",
            name="technology_database",
            field=models.JSONField(
                blank=True, default=list, verbose_name="تکنولوژی Database"
            ),
        ),
        migrations.AlterField(
            model_name="technologyused",
            name="technology_frontend",
            field=models.JSONField(
                blank=True, default=list, verbose_name="تکنولوژی Frontend"
            ),
        ),
        migrations.AlterField(
            model_name="technologyused",
            name="technology_infrastructure",
            field=models.JSONField(
                blank=True, default=list, verbose_name="تکنولوژی Infrastructure"
            ),
        ),
        migrations.AlterField(
            model_name="technologyused",
            name="technology_mobile",
            field=models.JSONField(
                blank=True, default=list, verbose_name="تکنولوژی Mobile"
            ),
        ),
        migrations.AlterField(
            model_name="technologyused",
            name="technology_third_party",
            field=models.JSONField(
                blank=True, default=list, verbose_name="سرویس\u200cهای جانبی"
            ),
        ),
        migrations.RemoveField(
            model_name="technologyused",
            name="technology_CMS",
        ),
        migrations.RemoveField(
            model_name="technologyused",
            name="technology_devOps",
        ),
        migrations.AddField(
            model_name="technologyused",
            name="technology_cms",
            field=models.JSONField(
                blank=True, default=list, verbose_name="CMS و فروشگاه\u200cساز"
            ),
        ),
        migrations.AddField(
            model_name="technologyused",
            name="technology_devops",
            field=models.JSONField(
                blank=True, default=list, verbose_name="تکنولوژی DevOps"
            ),
        ),
    ]
