# Generated by Django 4.2.16 on 2026-06-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_alter_technologyused_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand_industry_scope',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='حوزه / صنعت برند'),
        ),
        migrations.AddField(
            model_name='listing',
            name='brand_legal_status',
            field=models.CharField(blank=True, choices=[('registered', 'ثبت\u200cشده'), ('in_progress', 'در حال ثبت'), ('usage_right_only', 'فقط حق استفاده')], max_length=25, null=True, verbose_name='وضعیت حقوقی برند'),
        ),
        migrations.AddField(
            model_name='listing',
            name='brand_transferred_assets',
            field=models.TextField(blank=True, null=True, verbose_name='اجزای برند منتقل\u200cشده'),
        ),
        migrations.AddField(
            model_name='listing',
            name='brand_usage_restrictions',
            field=models.TextField(blank=True, null=True, verbose_name='محدودیت\u200cهای کاربرد برند'),
        ),
        migrations.AddField(
            model_name='listing',
            name='license_duration_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت مجوز (ماه)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='license_duration_type',
            field=models.CharField(blank=True, choices=[('permanent', 'دائمی'), ('limited', 'مدت\u200cدار')], max_length=20, null=True, verbose_name='نوع مدت مجوز'),
        ),
        migrations.AddField(
            model_name='listing',
            name='license_restrictions',
            field=models.TextField(blank=True, null=True, verbose_name='محدودیت\u200cهای مجوز'),
        ),
        migrations.AddField(
            model_name='listing',
            name='license_scope',
            field=models.TextField(blank=True, null=True, verbose_name='محدوده مجوز'),
        ),
        migrations.AddField(
            model_name='listing',
            name='ownership_document_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='وضعیت مالکیت / اسناد'),
        ),
        migrations.AddField(
            model_name='listing',
            name='ownership_transfer_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='شرایط انتقال مالکیت'),
        ),
        migrations.AddField(
            model_name='listing',
            name='partial_ownership_buyer_rights',
            field=models.TextField(blank=True, null=True, verbose_name='حقوق خریدار'),
        ),
        migrations.AddField(
            model_name='listing',
            name='partial_ownership_exit_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='شرایط خروج / فروش مجدد سهم'),
        ),
        migrations.AddField(
            model_name='listing',
            name='partial_ownership_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد سهم'),
        ),
        migrations.AddField(
            model_name='listing',
            name='partial_ownership_valuation_method',
            field=models.TextField(blank=True, null=True, verbose_name='فرمول / روش ارزش\u200cگذاری'),
        ),
        migrations.AddField(
            model_name='listing',
            name='revenue_share_base',
            field=models.CharField(blank=True, choices=[('gross', 'درآمد ناخالص'), ('net', 'درآمد خالص')], max_length=10, null=True, verbose_name='مبنای محاسبه'),
        ),
        migrations.AddField(
            model_name='listing',
            name='revenue_share_contract_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت قرارداد (ماه)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='revenue_share_minimum_guarantee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='حداقل تضمینی ماهانه'),
        ),
        migrations.AddField(
            model_name='listing',
            name='revenue_share_payment_period',
            field=models.CharField(blank=True, choices=[('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'فصلی')], max_length=20, null=True, verbose_name='دوره پرداخت'),
        ),
        migrations.AddField(
            model_name='listing',
            name='revenue_share_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد سهم از درآمد'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('full_ownership', 'فروش مالکیت / انتقال کامل'), ('partial_ownership', 'فروش مالکیت بخشی / سهمی'), ('license', 'فروش مجوز / لایسنس'), ('revenue_share', 'فروش سهم از درآمد'), ('brand', 'فروش برند')], max_length=20, null=True, verbose_name='نوع فروش'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='areas_activity',
            field=models.CharField(choices=[('shopping_commerce', 'فروشگاهی و تجارت الکترونیک'), ('technology_software', 'تکنولوژی و نرم\u200cافزار'), ('education_learning', 'آموزش و یادگیری'), ('health_medicine_beauty', 'سلامت، پزشکی و زیبایی'), ('news_magazines_portals', 'خبری، مجله و پورتال'), ('finance_stock_exchange_cryptocurrency', 'مالی، بورس و ارز دیجیتال'), ('entertainment_games_movies', 'سرگرمی، بازی و فیلم'), ('lifestyle_fashion_fashion', 'سبک زندگی، مد و فشن'), ('travel_tourism_immigration', 'سفر، گردشگری و مهاجرت'), ('real_estate', 'املاک و مستغلات'), ('corporate_B2B_services', 'خدمات شرکتی و B2B'), ('sports_fitness', 'ورزشی و تناسب اندام'), ('food_cooking_restaurants', 'غذا، آشپزی و رستوران'), ('home_decoration_architecture', 'خانه، دکوراسیون و معماری'), ('pets', 'حیوانات خانگی'), ('other', 'سایر')], max_length=60, verbose_name='حوزه\u200c فعالیت'),
        ),
        migrations.AlterField(
            model_name='monetizationmethod',
            name='method',
            field=models.CharField(choices=[('banner_click_advertising', 'تبلیغات بنری و کلیکی'), ('sponsored_posts', 'پست\u200cهای حمایت\u200cشده'), ('cooperation_sales', 'همکاری در فروش'), ('special_subscription_sale', 'فروش اشتراک ویژه'), ('selling_digital_products', 'فروش محصولات دیجیتال'), ('selling_physical_products', 'فروش محصولات فیزیکی'), ('receive_financial_support', 'دریافت حمایت مالی'), ('holding_training_courses', 'برگزاری دوره\u200cهای آموزشی و وبینار'), ('sell_backlinks', 'فروش بک\u200cلینک و فضای تبلیغاتی'), ('providing_consulting_services', 'ارائه خدمات مشاوره و فریلنسری')], max_length=50, verbose_name='روش'),
        ),
    ]
