# Generated by Django 4.2.16 on 2026-09-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_remove_listing_asset_details_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='asset_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اختصاصی دارایی'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('website_blog', 'وبلاگ / بلاگ محتوایی'), ('website_news_magazine', 'خبری و مجله آنلاین'), ('website_forum_community', 'انجمن و جامعه آنلاین (فروم)'), ('website_directory', 'دایرکتوری و نیازمندی'), ('website_portal', 'پرتال چندمنظوره'), ('website_review', 'وبسایت بررسی و ریویو'), ('website_landing_page', 'لندینگ پیج / صفحه فروش'), ('website_corporate', 'وبسایت شرکتی و معرفی کسب\u200cوکار'), ('website_educational', 'وبسایت آموزشی / دوره آنلاین'), ('website_job_board', 'کاریابی و آگهی استخدام'), ('website_dating', 'وبسایت آشنایی و دوستیابی'), ('website_real_estate', 'وبسایت آگهی املاک'), ('website_classifieds', 'وبسایت نیازمندی و آگهی عمومی'), ('website_other', 'سایر وبسایت\u200cها'), ('ecommerce_woocommerce', 'فروشگاه ووکامرس (WordPress)'), ('ecommerce_shopify', 'فروشگاه شاپیفای'), ('ecommerce_opencart_prestashop', 'فروشگاه اوپن\u200cکارت / پرستاشاپ'), ('ecommerce_custom', 'فروشگاه با کدنویسی اختصاصی'), ('ecommerce_marketplace_shop', 'فروشگاه داخل مارکت\u200cپلیس (دیجی\u200cکالا، باسلام و ...)'), ('ecommerce_dropship', 'فروشگاه دراپ\u200cشیپینگ'), ('ecommerce_digital_products', 'فروش محصولات دیجیتال'), ('ecommerce_physical_products', 'فروش محصولات فیزیکی'), ('ecommerce_subscription_box', 'اشتراک دوره\u200cای محصول (Subscription Box)'), ('ecommerce_other', 'سایر فروشگاه\u200cهای اینترنتی'), ('app_android', 'اپلیکیشن اندروید'), ('app_ios', 'اپلیکیشن iOS'), ('app_cross_platform', 'اپلیکیشن کراس\u200cپلتفرم (Flutter / React Native)'), ('app_pwa', 'وب\u200cاپلیکیشن (PWA)'), ('app_desktop', 'نرم\u200cافزار دسکتاپ'), ('app_game_mobile', 'بازی موبایل'), ('app_game_pc_console', 'بازی PC / کنسول'), ('app_saas', 'اپلیکیشن / سرویس SaaS'), ('app_browser_extension', 'اکستنشن مرورگر'), ('app_telegram_bot', 'ربات تلگرام'), ('app_other', 'سایر اپلیکیشن\u200cها'), ('social_instagram', 'پیج اینستاگرام'), ('social_telegram_channel', 'کانال تلگرام'), ('social_telegram_group', 'گروه تلگرام'), ('social_youtube', 'کانال یوتیوب'), ('social_aparat', 'کانال آپارات'), ('social_twitter_x', 'پیج توییتر / X'), ('social_facebook', 'پیج فیسبوک'), ('social_linkedin', 'پیج لینکدین'), ('social_tiktok', 'پیج تیک\u200cتاک'), ('social_pinterest', 'پیج پینترست'), ('social_threads', 'پیج تردز (Threads)'), ('social_clubhouse', 'اکانت کلاب\u200cهاوس'), ('social_other', 'سایر شبکه\u200cهای اجتماعی'), ('content_podcast', 'پادکست'), ('content_newsletter', 'خبرنامه ایمیلی (Newsletter)'), ('content_adsense_channel', 'کانال درآمد از تبلیغات (AdSense / YPP)'), ('content_streaming', 'سرویس پخش زنده / استریمینگ'), ('content_ebook_course', 'کتاب الکترونیک و دوره ضبط\u200cشده'), ('content_stock_media', 'فروش عکس/ویدیو استوک'), ('content_other', 'سایر محتوا و رسانه'), ('domain_com', 'دامنه .com'), ('domain_ir', 'دامنه .ir'), ('domain_international_other', 'سایر دامنه\u200cهای بین\u200cالمللی (.net, .org, ...)'), ('domain_brandable', 'دامنه برندی / کوتاه'), ('domain_keyword', 'دامنه کلمه کلیدی (Exact Match)'), ('domain_portfolio', 'مجموعه دامنه (Domain Portfolio)'), ('service_agency', 'آژانس / تیم خدماتی (طراحی، سئو، مارکتینگ)'), ('service_freelance_platform', 'پلتفرم فریلنسری'), ('service_consulting', 'مشاوره و کوچینگ آنلاین'), ('service_membership_site', 'سایت عضویت / اشتراک ویژه'), ('service_marketplace', 'مارکت\u200cپلیس واسط خرید و فروش'), ('service_booking', 'سیستم رزرو و نوبت\u200cدهی آنلاین'), ('service_other', 'سایر کسب\u200cوکارهای خدماتی'), ('other_misc', 'متفرقه')], max_length=40, null=True, verbose_name='دسته\u200cبندی'),
        ),
    ]
