# Generated by Django 4.2.16 on 2026-09-12 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_listing_asset_details_alter_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_stack', models.CharField(blank=True, max_length=300, verbose_name='تکنولوژی\u200cهای سایت')),
                ('monthly_visits', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='بازدید ماهانه')),
                ('unique_visitors', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='کاربران یکتای ماهانه')),
                ('page_views', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='بازدید صفحات ماهانه')),
                ('pages_indexed', models.PositiveIntegerField(blank=True, null=True, verbose_name='صفحات ایندکس\u200cشده گوگل')),
                ('domain_authority', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Domain Authority')),
                ('backlinks_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد بک\u200cلینک')),
                ('content_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد مقالات / پست\u200cها')),
                ('seo_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز سئو (0-100)')),
                ('bounce_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ پرش (%)')),
                ('avg_session_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='میانگین مدت بازدید (ثانیه)')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_details', to='listings.listing', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'جزئیات وب\u200cسایت',
                'verbose_name_plural': 'جزئیات وب\u200cسایت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(blank=True, max_length=100, verbose_name='نام کاربری / Handle')),
                ('followers', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='تعداد فالوور')),
                ('following', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد Following')),
                ('posts_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد پست\u200cها')),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ تعامل (%)')),
                ('avg_reach', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='میانگین ریچ هر پست')),
                ('avg_story_views', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='میانگین بازدید استوری')),
                ('post_frequency', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد پست در هفته')),
                ('audience_country', models.CharField(blank=True, max_length=100, verbose_name='کشور اصلی مخاطبان')),
                ('audience_gender', models.CharField(blank=True, max_length=50, verbose_name='جنسیت غالب مخاطبان')),
                ('audience_age_range', models.CharField(blank=True, max_length=50, verbose_name='بازه سنی مخاطبان')),
                ('is_monetized', models.BooleanField(default=False, verbose_name='مونتیزه شده')),
                ('has_verification', models.BooleanField(default=False, verbose_name='دارای تیک آبی')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_details', to='listings.listing', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'جزئیات پیج/کانال',
                'verbose_name_plural': 'جزئیات پیج\u200cها/کانال\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ServiceBusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_list', models.TextField(blank=True, verbose_name='خدمات ارائه\u200cشده')),
                ('team_size', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='اندازه تیم')),
                ('active_clients', models.PositiveIntegerField(blank=True, null=True, verbose_name='مشتریان فعال')),
                ('total_clients', models.PositiveIntegerField(blank=True, null=True, verbose_name='کل مشتریان')),
                ('avg_project_value', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='میانگین ارزش پروژه (تومان)')),
                ('monthly_projects', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد پروژه در ماه')),
                ('client_retention', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ حفظ مشتری (%)')),
                ('contracts_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='قراردادهای فعال')),
                ('recurring_revenue_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد درآمد تکرارشونده (%)')),
                ('has_registered_brand', models.BooleanField(default=False, verbose_name='برند ثبت\u200cشده دارد')),
                ('has_physical_office', models.BooleanField(default=False, verbose_name='دفتر فیزیکی دارد')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='listings.listing', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'جزئیات کسب\u200cوکار خدماتی',
                'verbose_name_plural': 'جزئیات کسب\u200cوکارهای خدماتی',
            },
        ),
        migrations.CreateModel(
            name='EcommerceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد محصولات')),
                ('orders_per_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='سفارش ماهانه')),
                ('aov', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='میانگین ارزش سفارش (تومان)')),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ تبدیل (%)')),
                ('returning_customers', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='مشتریان بازگشتی (%)')),
                ('shipping_partners', models.CharField(blank=True, max_length=300, verbose_name='شرکت\u200cهای حمل\u200cونقل')),
                ('inventory_value', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='ارزش موجودی انبار (تومان)')),
                ('cart_abandonment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ رهاسازی سبد (%)')),
                ('suppliers_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد تامین\u200cکنندگان')),
                ('has_inventory', models.BooleanField(default=False, verbose_name='دارای انبار فعال')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_details', to='listings.listing', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'جزئیات فروشگاه',
                'verbose_name_plural': 'جزئیات فروشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DomainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='نام دامنه')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='پسوند')),
                ('registrar', models.CharField(blank=True, max_length=200, verbose_name='ثبت\u200cکننده (Registrar)')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('domain_age_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='سن دامنه (سال)')),
                ('monthly_type_in', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ترافیک تایپ-این ماهانه')),
                ('backlinks_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد بک\u200cلینک')),
                ('keyword', models.CharField(blank=True, max_length=200, verbose_name='کلمه کلیدی اصلی')),
                ('search_volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم جستجوی ماهانه')),
                ('cpc', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='CPC کلمه کلیدی (تومان)')),
                ('is_brandable', models.BooleanField(default=False, verbose_name='برندی / کوتاه')),
                ('is_exact_match', models.BooleanField(default=False, verbose_name='Exact Match Domain')),
                ('has_history', models.BooleanField(default=False, verbose_name='سابقه سایت قبلی دارد')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_details', to='listings.listing', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'جزئیات دامنه',
                'verbose_name_plural': 'جزئیات دامنه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ContentMediaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, choices=[('podcast', 'پادکست'), ('newsletter', 'خبرنامه ایمیلی'), ('youtube', 'کانال یوتیوب'), ('blog', 'وبلاگ محتوایی'), ('video', 'ویدیویی'), ('ebook', 'کتاب الکترونیک'), ('course', 'دوره آموزشی'), ('other', 'سایر')], max_length=20, verbose_name='نوع محتوا')),
                ('subscribers', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='تعداد مشترکین')),
                ('monthly_audience', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مخاطبان ماهانه')),
                ('episodes_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد قسمت\u200cها/شماره\u200cها')),
                ('publishing_frequency', models.CharField(blank=True, max_length=50, verbose_name='دوره انتشار')),
                ('avg_engagement', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='میانگین تعامل هر قسمت')),
                ('platforms', models.CharField(blank=True, max_length=300, verbose_name='پلتفرم\u200cهای انتشار')),
                ('avg_downloads', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='میانگین دانلود/پخش هر قسمت')),
                ('open_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ باز شدن ایمیل (%)')),
                ('click_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ کلیک (%)')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_details', to='listings.listing', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'جزئیات رسانه',
                'verbose_name_plural': 'جزئیات رسانه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloads', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='تعداد کل دانلود')),
                ('active_installs', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='نصب\u200cهای فعال')),
                ('dau', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='کاربران فعال روزانه')),
                ('mau', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='کاربران فعال ماهانه')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='امتیاز (از ۵)')),
                ('reviews_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد نظرات')),
                ('retention_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ نگهداشت (%)')),
                ('current_version', models.CharField(blank=True, max_length=50, verbose_name='نسخه فعلی')),
                ('last_update_date', models.CharField(blank=True, max_length=50, verbose_name='آخرین بروزرسانی')),
                ('has_in_app_purchase', models.BooleanField(default=False, verbose_name='خرید درون\u200cبرنامه\u200cای')),
                ('crash_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ کرش (%)')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_details', to='listings.listing', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'جزئیات اپلیکیشن',
                'verbose_name_plural': 'جزئیات اپلیکیشن\u200cها',
            },
        ),
    ]
