# Generated by Django 4.2.16 on 2026-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0046_websitedetails_socialmediadetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='platform',
            field=models.CharField(choices=[('website_blog', 'وبلاگ و سایت محتوایی'), ('website_news_magazine', 'خبری و مجله آنلاین'), ('content_podcast', 'پادکست و کانال صوتی'), ('content_newsletter', 'خبرنامه و ایمیل مارکتینگ'), ('content_adsense_channel', 'سایت درآمدزا (تبلیغات)'), ('content_ebook_course', 'کتاب الکترونیکی و دوره ضبط\u200cشده'), ('website_other', 'سایر محتوایی'), ('ecommerce_woocommerce', 'فروشگاه وردپرسی (ووکامرس)'), ('ecommerce_shopify', 'فروشگاه شاپیفای'), ('ecommerce_custom', 'فروشگاه اختصاصی'), ('ecommerce_marketplace_shop', 'فروشگاه در مارکت\u200cپلیس (قطعی، دیجیکالا، ترکیب)'), ('ecommerce_dropship', 'فروشگاه دراپ\u200cشیپینگ'), ('ecommerce_woo_fba_dropship', 'فروشگاه تحت\u200cسقف یا سفارش\u200cسازی'), ('ecommerce_other', 'سایر فروشگاه\u200cها'), ('app_saas', 'سرویس SaaS / درج شده\u200cای'), ('app_android', 'اپلیکیشن اندروید'), ('app_ios', 'اپلیکیشن iOS'), ('app_cross_platform', 'اپلیکیشن کراس\u200cپلتفرم'), ('app_game_mobile', 'بازی موبایل'), ('app_telegram_bot', 'ربات و ابزار تلگرام'), ('app_web_tool', 'ابزار و وب\u200cاپلیکیشن'), ('app_other', 'سایر نرم\u200cافزارها'), ('social_instagram', 'حساب و صفحه اینستاگرام'), ('social_telegram_channel', 'کانال تلگرام'), ('social_telegram_group', 'گروه و کمیونیتی تلگرام'), ('social_youtube', 'کانال یوتیوب'), ('social_aparat', 'کانال آپارات'), ('social_twitter_x', 'حساب توییتر / X'), ('social_tiktok', 'کانال تیک\u200cتاک'), ('website_forum_community', 'انجمن و فروم آنلاین'), ('social_linkedin', 'صفحه و پروفایل LinkedIn'), ('social_other', 'سایر شبکه\u200cهای اجتماعی'), ('service_agency', 'آژانس دیجیتال / تیم خدماتی'), ('service_consulting', 'مشاوره و کوچینگ'), ('service_membership_site', 'سایت اشتراک ویژه (محتوای محدود)'), ('service_marketplace', 'مارکت\u200cپلیس و پلتفرم معاملاتی'), ('service_booking', 'سیستم رزرو، نوبت\u200cدهی و جلسه\u200cبندی'), ('website_educational', 'پلتفرم آموزشی و دوره آنلاین'), ('website_job_board', 'پورتال کاریابی و استخدام'), ('website_real_estate', 'سایت و پلتفرم املاک'), ('service_sms_marketing', 'سرویس ارسال پیامک و ایمیل'), ('service_other', 'سایر خدمات'), ('domain_ir', 'دامنه .ir'), ('domain_com', 'دامنه .com'), ('domain_international_other', 'سایر دامنه\u200cهای بین\u200cالمللی'), ('domain_brandable', 'دامنه برندی و کوتاه'), ('domain_portfolio', 'مجموعه دامنه'), ('other_misc', 'متفرقه و سایر دارایی\u200cها')], max_length=40, verbose_name='نوع پلتفرم (زیرمجموعه)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('website_blog', 'وبلاگ و سایت محتوایی'), ('website_news_magazine', 'خبری و مجله آنلاین'), ('content_podcast', 'پادکست و کانال صوتی'), ('content_newsletter', 'خبرنامه و ایمیل مارکتینگ'), ('content_adsense_channel', 'سایت درآمدزا (تبلیغات)'), ('content_ebook_course', 'کتاب الکترونیکی و دوره ضبط\u200cشده'), ('website_other', 'سایر محتوایی'), ('ecommerce_woocommerce', 'فروشگاه وردپرسی (ووکامرس)'), ('ecommerce_shopify', 'فروشگاه شاپیفای'), ('ecommerce_custom', 'فروشگاه اختصاصی'), ('ecommerce_marketplace_shop', 'فروشگاه در مارکت\u200cپلیس (قطعی، دیجیکالا، ترکیب)'), ('ecommerce_dropship', 'فروشگاه دراپ\u200cشیپینگ'), ('ecommerce_woo_fba_dropship', 'فروشگاه تحت\u200cسقف یا سفارش\u200cسازی'), ('ecommerce_other', 'سایر فروشگاه\u200cها'), ('app_saas', 'سرویس SaaS / درج شده\u200cای'), ('app_android', 'اپلیکیشن اندروید'), ('app_ios', 'اپلیکیشن iOS'), ('app_cross_platform', 'اپلیکیشن کراس\u200cپلتفرم'), ('app_game_mobile', 'بازی موبایل'), ('app_telegram_bot', 'ربات و ابزار تلگرام'), ('app_web_tool', 'ابزار و وب\u200cاپلیکیشن'), ('app_other', 'سایر نرم\u200cافزارها'), ('social_instagram', 'حساب و صفحه اینستاگرام'), ('social_telegram_channel', 'کانال تلگرام'), ('social_telegram_group', 'گروه و کمیونیتی تلگرام'), ('social_youtube', 'کانال یوتیوب'), ('social_aparat', 'کانال آپارات'), ('social_twitter_x', 'حساب توییتر / X'), ('social_tiktok', 'کانال تیک\u200cتاک'), ('website_forum_community', 'انجمن و فروم آنلاین'), ('social_linkedin', 'صفحه و پروفایل LinkedIn'), ('social_other', 'سایر شبکه\u200cهای اجتماعی'), ('service_agency', 'آژانس دیجیتال / تیم خدماتی'), ('service_consulting', 'مشاوره و کوچینگ'), ('service_membership_site', 'سایت اشتراک ویژه (محتوای محدود)'), ('service_marketplace', 'مارکت\u200cپلیس و پلتفرم معاملاتی'), ('service_booking', 'سیستم رزرو، نوبت\u200cدهی و جلسه\u200cبندی'), ('website_educational', 'پلتفرم آموزشی و دوره آنلاین'), ('website_job_board', 'پورتال کاریابی و استخدام'), ('website_real_estate', 'سایت و پلتفرم املاک'), ('service_sms_marketing', 'سرویس ارسال پیامک و ایمیل'), ('service_other', 'سایر خدمات'), ('domain_ir', 'دامنه .ir'), ('domain_com', 'دامنه .com'), ('domain_international_other', 'سایر دامنه\u200cهای بین\u200cالمللی'), ('domain_brandable', 'دامنه برندی و کوتاه'), ('domain_portfolio', 'مجموعه دامنه'), ('other_misc', 'متفرقه و سایر دارایی\u200cها')], max_length=40, null=True, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='followers_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='تعداد کاربر ها'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/images/', verbose_name='تصویر اصلی'),
        ),
    ]
