# Generated by Django 4.2.16 on 2026-05-06 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bank_account",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agent_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="نام نماینده"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agent_national_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="کد ملی نماینده"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agent_position",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="سمت نماینده"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="authorization_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/company_authorizations/",
                verbose_name="مدرک نمایندگی",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="business_category",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="دسته\u200cبندی کسب\u200cوکار"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="business_license",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/licenses/",
                verbose_name="مجوز کسب\u200cوکار",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="شهر"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="companies/logos/",
                verbose_name="لوگوی شرکت",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="نام شرکت"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_national_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="شناسه ملی شرکت"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_type",
            field=models.CharField(blank=True, max_length=100, verbose_name="نوع شرکت"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="economic_code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="کد اقتصادی"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "مرد"), ("female", "زن"), ("other", "سایر")],
                max_length=20,
                verbose_name="جنسیت",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="iban_number",
            field=models.CharField(blank=True, max_length=26, verbose_name="شماره شبا"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_seller_approved",
            field=models.BooleanField(default=False, verbose_name="تأیید فروشندگی"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="kyc_level",
            field=models.IntegerField(default=0, verbose_name="سطح احراز هویت"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="national_id_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="documents/national_ids/",
                verbose_name="تصویر کارت ملی",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="کد پستی"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="province",
            field=models.CharField(blank=True, max_length=100, verbose_name="استان"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="registration_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="شماره ثبت"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "خریدار"),
                    ("seller", "فروشنده"),
                    ("both", "خریدار / فروشنده"),
                ],
                default="buyer",
                max_length=20,
                verbose_name="نقش کاربر",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="selfie_with_id",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="documents/selfies/",
                verbose_name="سلفی با مدرک",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tax_info",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="اطلاعات مالیاتی"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("individual", "شخص حقیقی"), ("company", "شخص حقوقی")],
                default="individual",
                max_length=20,
                verbose_name="نوع کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ عضویت"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="احراز شده"),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True, verbose_name="کد ملی"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                verbose_name="شماره موبایل",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="نام بانک"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="بیو"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
