# Generated by Django 4.2.16 on 2026-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="نام"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="نام خانوادگی"
            ),
        ),
    ]
