# Generated by Django 4.2.16 on 2026-05-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_first_name_userprofile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نام"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نام خانوادگی"
            ),
        ),
    ]
