# Generated by Django 4.2.16 on 2026-05-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_address",
            field=models.EmailField(
                blank=True, max_length=150, null=True, verbose_name="ایمیل عمومی"
            ),
        ),
    ]
