# Generated by Django 4.2.16 on 2026-05-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userprofile_email_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_seller_approved",
        ),
    ]
