# Generated by Django 4.2.16 on 2026-05-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_userprofile_is_seller_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="premium",
            field=models.BooleanField(default=False, verbose_name="کاربر ویژه"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pro",
            field=models.BooleanField(default=False, verbose_name="کاربر پرو"),
        ),
    ]
