# Generated by Django 4.2.16 on 2026-05-08 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="category",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="closed_at",
        ),
        migrations.RemoveField(
            model_name="ticketmessage",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="ticketmessage",
            name="is_staff_reply",
        ),
        migrations.AddField(
            model_name="ticketmessage",
            name="is_admin_reply",
            field=models.BooleanField(default=False, verbose_name="پاسخ ادمین"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[("low", "کم"), ("medium", "متوسط"), ("high", "بالا")],
                default="medium",
                max_length=10,
                verbose_name="اولویت",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("answered", "پاسخ داده شده"),
                    ("closed", "بسته شده"),
                ],
                default="open",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="ticketmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="فرستنده",
            ),
        ),
        migrations.DeleteModel(
            name="TicketCategory",
        ),
    ]
