# Generated by Django 4.2.16 on 2026-05-08 21:28

from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_remove_ticket_category_remove_ticket_closed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.AddField(
            model_name="ticketmessage",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=tickets.models.ticket_attachment_path,
                validators=[tickets.models.validate_file_size],
                verbose_name="فایل پیوست",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="tickets.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
    ]
