# Generated by Django 4.2.16 on 2026-05-07 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0011_listing_about_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("visit_request", "درخواست بازدید"),
                            ("visit_approved", "تایید بازدید"),
                            ("visit_rejected", "رد بازدید"),
                            ("listing_approved", "تایید آگهی"),
                            ("listing_rejected", "رد آگهی"),
                            ("new_message", "پیام جدید"),
                        ],
                        max_length=20,
                        verbose_name="نوع اعلان",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="لینک عملیات"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                        verbose_name="آگهی",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گیرنده",
                    ),
                ),
                (
                    "visit_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.visitrequest",
                        verbose_name="درخواست بازدید",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
